package global.oei.domain.shared.publicprofile;

import java.util.Objects;

import global.oei.domain.shared.member.MemberId;
import global.oei.domain.shared.membership.MembershipTier;

/**
 * A member's digital business card (QR code + vCard link for {@code /card/{publicSlug}}).
 *
 * <p>Generated by {@code GenerateDigitalBusinessCardService}, the sole place allowed to
 * construct one: {@link #qrCodeUrl()}/{@link #vCardUrl()} are mocked deterministic URLs derived
 * from {@link #publicSlug()} — there is no real QR-image renderer or vCard file generator in
 * this iteration, mirroring {@code WalletPass}'s "mocked, no real integration" posture. Not
 * persisted: regenerated on every {@code generateDigitalCard} call from the member's current
 * {@link PublicProfile} and {@link MembershipTier}, so it is always in sync with them.</p>
 */
public record DigitalBusinessCard(MemberId memberId, String publicSlug, String qrCodeUrl, String vCardUrl, String theme, MembershipTier tier) {

    public DigitalBusinessCard {
        Objects.requireNonNull(memberId, "memberId must not be null");
        Objects.requireNonNull(publicSlug, "publicSlug must not be null");
        Objects.requireNonNull(qrCodeUrl, "qrCodeUrl must not be null");
        Objects.requireNonNull(vCardUrl, "vCardUrl must not be null");
        Objects.requireNonNull(theme, "theme must not be null");
    }
}
