-- Real certification chains from network-graph-mock.adapter.ts's CERTS constant, completing
-- the network_certification TODO. expertCount is a plausible static demo figure (no
-- expert<->certification link table exists yet -- TODO for a future iteration).

INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-aws-1', 'cloud-t1', 'cloud', 'AWS Cloud Practitioner', 'AWS', NULL, 'AWS Cloud Practitioner (AWS)', 'Cloud,IaC', '3 ans', 6, 780, -400) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-aws-2', 'cloud-t1', 'cloud', 'AWS Developer Associate', 'AWS', 'cert-aws-1', 'AWS Developer Associate (AWS)', 'Cloud,IaC', '3 ans', 6, 820, -370) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-aws-3', 'cloud-t1', 'cloud', 'AWS Solutions Architect', 'AWS', 'cert-aws-2', 'AWS Solutions Architect (AWS)', 'Cloud,IaC', '3 ans', 6, 860, -340) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-azure-1', 'cloud-t2', 'cloud', 'Azure Fundamentals AZ-900', 'Microsoft', NULL, 'Azure Fundamentals AZ-900 (Microsoft)', 'Cloud,Administration', '2 ans', 4, 900, -280) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-azure-2', 'cloud-t2', 'cloud', 'Azure Administrator AZ-104', 'Microsoft', 'cert-azure-1', 'Azure Administrator AZ-104 (Microsoft)', 'Cloud,Administration', '2 ans', 4, 940, -250) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-k8s-1', 'cloud-t1', 'cloud', 'CKA — Kubernetes Administrator', 'Linux Foundation', NULL, 'CKA — Kubernetes Administrator (Linux Foundation)', 'Kubernetes,Orchestration', '3 ans', 5, 700, -480) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-ssi-1', 'cyber-t2', 'cyber', 'CISSP', 'ISC²', NULL, 'CISSP (ISC²)', 'Gouvernance,Sécurité', '3 ans', 4, -700, -260) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-ssi-2', 'cyber-t2', 'cyber', 'ISO 27001 Lead Implementer', 'PECB', 'cert-ssi-1', 'ISO 27001 Lead Implementer (PECB)', 'Gouvernance,Sécurité', '3 ans', 4, -660, -230) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-pentest-1', 'cyber-t1', 'cyber', 'CEH — Certified Ethical Hacker', 'EC-Council', NULL, 'CEH — Certified Ethical Hacker (EC-Council)', 'Pentest,Sécurité offensive', '3 ans', 3, -880, -380) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-ml-1', 'ia-t1', 'ia', 'TensorFlow Developer', 'Google', NULL, 'TensorFlow Developer (Google)', 'Machine Learning', 'Aucune', 3, -180, -600) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-genai-1', 'ia-t2', 'ia', 'Azure AI Engineer AI-102', 'Microsoft', NULL, 'Azure AI Engineer AI-102 (Microsoft)', 'IA Générative', '2 ans', 2, 20, -600) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-dataeng-1', 'data-t1', 'data', 'Databricks Data Engineer', 'Databricks', NULL, 'Databricks Data Engineer (Databricks)', 'Data Engineering', '2 ans', 3, 540, 200) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-togaf-1', 'archi-t1', 'archi', 'TOGAF 10 Foundation', 'The Open Group', NULL, 'TOGAF 10 Foundation (The Open Group)', 'Architecture d''entreprise', 'Aucune', 5, -1000, 300) ON CONFLICT (id) DO NOTHING;
INSERT INTO network_certification (id, topic_id, domain_id, label, provider, prereq_certification_id, description, validated_skills, validity_period, expert_count, x, y) VALUES ('cert-java-1', 'soft-t1', 'soft', 'Oracle Java SE 17 Professional', 'Oracle', NULL, 'Oracle Java SE 17 Professional (Oracle)', 'Java', 'Aucune', 4, -400, 60) ON CONFLICT (id) DO NOTHING;

-- 14 certifications across 10 chains inserted above.
