import { Routes } from '@angular/router';
import { Home } from './presentation/pages/home/home';
import { APropos } from './presentation/pages/a-propos/a-propos';
import { NosMissions } from './presentation/pages/nos-missions/nos-missions';
import { Deontologie } from './presentation/pages/deontologie/deontologie';
import { Certifications } from './presentation/pages/certifications/certifications';
import { Ressources } from './presentation/pages/ressources/ressources';
import { Actualites } from './presentation/pages/actualites/actualites';
import { Contact } from './presentation/pages/contact/contact';
import { MentionsLegales } from './presentation/pages/mentions-legales/mentions-legales';
import { PlanDuSite } from './presentation/pages/plan-du-site/plan-du-site';
import { MembresFondateurs } from './presentation/pages/membres-fondateurs/membres-fondateurs';
import { Publications } from './presentation/pages/publications/publications';
import { Partenaires } from './presentation/pages/partenaires/partenaires';
import { PartenaireDetail } from './presentation/pages/partenaire-detail/partenaire-detail';
import { DomaineDetail } from './presentation/pages/domaine-detail/domaine-detail';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'a-propos', component: APropos },
  { path: 'nos-missions', component: NosMissions },
  { path: 'deontologie', component: Deontologie },
  { path: 'certifications', component: Certifications },
  { path: 'ressources', component: Ressources },
  { path: 'actualites', component: Actualites },
  { path: 'publications', component: Publications },
  { path: 'partenaires', component: Partenaires },
  { path: 'partenaires/:id', component: PartenaireDetail },
  { path: 'domaines/:slug', component: DomaineDetail },
  { path: 'contact', component: Contact },
  { path: 'membres-fondateurs', component: MembresFondateurs },
  { path: 'mentions-legales', component: MentionsLegales },
  { path: 'plan-du-site', component: PlanDuSite },
];
